language: python
python:
  - "3.6"
  - "3.7-dev"
cache: pip
env:
  global:
    - CI=true
  matrix:
    -TEST_DOC=false
    -TEST_DOC=true
install:
  - pip install -r requirements.txt

script: 
  - python test_grabbingTheWeather.py
